---
- name: set config and keys paths
  set_fact:
    ceph_config_keys:
      - /etc/ceph/ceph.conf
      - /etc/ceph/ceph.client.admin.keyring
      - /etc/ceph/ceph.mon.keyring
      - /etc/ceph/monmap-{{ cluster }}
      - /var/lib/ceph/bootstrap-osd/ceph.keyring

- name: stat for ceph config and keys
  local_action: stat path={{ fetch_directory }}/docker_mon_files/{{ item }}
  with_items: ceph_config_keys
  changed_when: false
  become: false
  failed_when: false
  register: statconfig

- name: ensure conf dirs exist
  file: path={{ item }} state=directory
  with_items:
  - /etc/ceph
  - /var/lib/ceph/bootstrap-osd/

- name: try to copy ceph config and keys
  copy:
    src: "{{ playbook_dir }}/{{ fetch_directory }}/docker_mon_files/{{ item }}"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  changed_when: false
  with_items: ceph_config_keys
