---
# For openstack VMs modify the mount point below depending on if the Openstack
# VM deploy tool defaults to mounting ephemeral disks
- name: umount ceph disk (if on openstack)
  mount:
    name: /mnt
    src: /dev/vdb
    fstype: ext3
    state: unmounted
  when: ceph_docker_on_openstack

- name: verify if the disk was already prepared
  shell: "lsblk -o PARTLABEL {{ item }} | grep -sq 'ceph'"
  failed_when: false
  with_items: ceph_osd_docker_devices
  register: osd_prepared

## use shell rather than docker module
## to ensure osd disk prepare finishes before
## starting the next task
#- name: prepare ceph osd disk
#  shell: |
#    docker run --net=host \
#    --pid=host \
#    --privileged=true \
#    --name="{{ ansible_hostname }}-osd-prepare-{{ item.0 |
#    regex_replace('/', '') }}" \
#    -v /etc/ceph:/etc/ceph \
#    -v /var/lib/ceph/:/var/lib/ceph/ \
#    -v /dev:/dev \
#    -v /etc/localtime:/etc/localtime:ro \
#    -e "OSD_DEVICE={{ item.0 }}" \
#    -e "{{ ceph_osd_docker_prepare_env }}" \
#    -e CEPH_DAEMON=OSD_CEPH_DISK_PREPARE \
#    "{{ ceph_osd_docker_username }}/{{ ceph_osd_docker_imagename }}:{{ ceph_osd_docker_image_tag }}"
#  with_together:
#    - ceph_osd_docker_devices
#    - osd_prepared.results
#  when:
#    - item.1.get("rc", 0) != 0
#    - ceph_osd_docker_prepare_env is defined
#    - not osd_containerized_deployment_with_kv
#    - not osd_directory
#    - site != 'cloudlab'
#    - site != 'piha'

- name: prepare ceph osd disk with kv_store
  shell: |
    docker run  --net=host   \
    --pid=host \
    --privileged=true \
    --name="{{ ansible_hostname }}-osd-prepare-{{ item.0 |
    regex_replace('/', '') }}" \
    -v /dev:/dev \
    -v /etc/localtime:/etc/localtime:ro \
    -e "OSD_DEVICE={{ item.0 }}" \
    -e "{{ ceph_osd_docker_prepare_env }}" \
    -e CEPH_DAEMON=OSD_CEPH_DISK_PREPARE \
    -e KV_TYPE={{kv_type}} \
    -e KV_IP={{kv_endpoint}} \
    -e KV_PORT={{kv_port}} \
    "{{ ceph_osd_docker_username }}/{{ ceph_osd_docker_imagename }}:{{ ceph_osd_docker_image_tag }}" \
  with_together:
    - ceph_osd_docker_devices
    - osd_prepared.results
  when:
    - item.1.get("rc", 0) != 0
    - ceph_osd_docker_prepare_env is defined
    - osd_containerized_deployment_with_kv

# Use systemd to manage container on appropriate host
- name: generate systemd unit file
  become: true
  template:
    src: "{{ role_path }}/templates/ceph-osd.service.j2"
    dest: /etc/systemd/system/ceph-osd@.service
    owner: "root"
    group: "root"
    mode: "0644"
  failed_when: false
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'CoreOS'

- name: enable systemd unit file for osd instance
  shell: systemctl enable ceph-osd@{{ item | basename }}.service
  failed_when: false
  changed_when: false
  with_items: ceph_osd_docker_devices
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'CoreOS'

- name: reload systemd unit files
  shell: systemctl daemon-reload
  changed_when: false
  failed_when: false
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'CoreOS'

- name: systemd start osd container
  service:
    name: ceph-osd@{{ item | basename }}
    state: started
    enabled: yes
  changed_when: false
  with_items: ceph_osd_docker_devices
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'CoreOS'

#- name: run the ceph osd docker image
#  shell: >
#         docker run -d \
#         --name "{{ ansible_hostname }}-osd-{{ item | regex_replace('/', '') }}" \
#         --net host \
#         --pid host \
#         --privileged \
#         -e "OSD_DEVICE={{ item }}" \
#         -e "{{ ceph_osd_docker_extra_env }}" \
#         -v "/var/lib/ceph:/var/lib/ceph" \
#         -v "/etc/ceph:/etc/ceph" \
#         -v "/etc/localtime:/etc/localtime:ro" \
#         -v "/dev:/dev" \
#         -v "/run:/run" \
#         "{{ ceph_osd_docker_username }}/{{ ceph_osd_docker_imagename }}:{{ ceph_osd_docker_image_tag }}"
#  with_items: ceph_osd_docker_devices
#  when:
#    - ansible_os_family != 'RedHat'
#    - ansible_os_family != 'CoreOS'
#    - not osd_containerized_deployment_with_kv
#    - not osd_directory
#    - site != 'cloudlab'
#    - site != 'piha'

- name: run the ceph osd docker image via cloudlab
  shell: >
         docker run -d -it \
         --name "{{ ansible_hostname }}-osd-{{ item | regex_replace('/', '') }}" \
         --net host \
         --pid host \
         --privileged \
         -e "OSD_DEVICE={{ item }}" \
         -e "{{ ceph_osd_docker_extra_env }}" \
         -v "/var/lib/ceph:/var/lib/ceph" \
         -v "/etc/ceph:/etc/ceph" \
         -v "/etc/localtime:/etc/localtime:ro" \
         -v "/dev:/dev" \
         -v "/run:/run" \
         --entrypoint=/bin/bash \
         "{{ ceph_osd_docker_username }}/{{ ceph_osd_docker_imagename }}:{{ ceph_osd_docker_image_tag }}"
  with_items: ceph_osd_docker_devices

- name: erase the damage of other osd stuff
  shell: sgdisk --zap-all --clear --mbrtogpt -g -- {{ item }}
  with_items: ceph_osd_docker_devices

- name: partition the disk
  shell: sgdisk -n 1:0:+10G -n 2:20973568:+{{ osd_data_size }}G -g {{ item }}
  with_items: ceph_osd_docker_devices

- name: make the OSD directory
  shell: docker exec "{{ ansible_hostname }}-osd-{{ item | regex_replace('/', '') }}" mkdir -p /var/lib/ceph/osd
  with_items: ceph_osd_docker_devices
  
- name: partition the disk
  shell: docker exec "{{ ansible_hostname }}-osd-{{ item | regex_replace('/', '') }}" ceph-disk prepare --cluster ceph --cluster-uuid e9570dd8-03ad-45f0-8a74-ec9b3bb7095f --fs-type ext4 {{ item }}1 {{ item }}2
  with_items: ceph_osd_docker_devices

- name: fix some permissions
  shell: docker exec "{{ ansible_hostname }}-osd-{{ item | regex_replace('/', '') }}" chown ceph {{ item }}1 {{ item }}2
  with_items: ceph_osd_docker_devices

- name: activate the disk
  shell: docker exec "{{ ansible_hostname }}-osd-{{ item | regex_replace('/', '') }}" ceph-disk activate {{ item }}1
  ignore_errors: true
  with_items: ceph_osd_docker_devices

- name: start the OSD
  shell: docker exec "{{ ansible_hostname }}-osd-{{ item | regex_replace('/', '') }}" ceph-osd -i `ls /var/lib/ceph/osd/ | sed "s/-/ /g" | awk '{print $2}'`
  with_items: ceph_osd_docker_devices

- name: add to the crush map
  shell: docker exec "{{ ansible_hostname }}-osd-{{ item | regex_replace('/', '') }}" ceph osd crush add osd.`ls /var/lib/ceph/osd/ | sed "s/-/ /g" | awk '{print $2}'` 1.0 host=`hostname`
  with_items: ceph_osd_docker_devices

- name: move server under root crush node (may be redundant)
  shell: docker exec "{{ ansible_hostname }}-osd-{{ item | regex_replace('/', '') }}" ceph osd crush move `hostname` root=default
  with_items: ceph_osd_docker_devices

- name: run the ceph osd docker image with a directory
  shell: >
         docker run -d -it \
         --name "pl3-osd-ceph_osd_docker_devices" \
         --net host \
         --pid host \
         --privileged \
         -e "OSD_DEVICE=ceph_osd_docker_devices" \
         -e "CEPH_DAEMON=OSD_DIRECTORY" \
         -e "{{ ceph_osd_docker_extra_env }}" \
         -v "/var/lib/ceph/:/var/lib/ceph" \
         -v "/etc/ceph:/etc/ceph" \
         -v "/etc/localtime:/etc/localtime:ro" \
         -v "/dev:/dev" \
         -v "/run:/run" \
         "{{ ceph_osd_docker_username }}/{{ ceph_osd_docker_imagename }}:{{ ceph_osd_docker_image_tag }}"
  when:
    - osd_directory

- name: run the ceph osd docker image with kv
  docker:
    image: "{{ ceph_osd_docker_username }}/{{ ceph_osd_docker_imagename }}:{{ ceph_osd_docker_image_tag }}"
    name: "{{ ansible_hostname }}-osd-{{ item | regex_replace('/', '') }}"
    net: host
    pid: host
    state: running
    privileged: yes
    env: "KV_TYPE={{kv_type}},KV_IP={{kv_endpoint}},OSD_DEVICE={{ item }},{{ ceph_osd_docker_extra_env }}"
    volumes: "/etc/localtime:/etc/localtime:ro,/dev/:/dev/"
  with_items: ceph_osd_docker_devices
  when:
   - ansible_os_family != 'RedHat'
   - ansible_os_family != 'CoreOS'
   - osd_containerized_deployment_with_kv
 
