---
# For openstack VMs modify the mount point below depending on if the Openstack
# VM deploy tool defaults to mounting ephemeral disks
- name: umount ceph disk (if on openstack)
  mount:
    name: /mnt
    src: /dev/vdb
    fstype: ext3
    state: unmounted
  when: ceph_docker_on_openstack

- name: verify if the disk was already prepared
  shell: "lsblk -o PARTLABEL {{ item }} | grep -sq 'ceph'"
  failed_when: false
  changed_when: false
  with_items: ceph_osd_docker_devices
  register: osd_prepared

- name: start OSD container in the background 
  shell: >
         docker run \
           -it -d \
           --name "{{ ansible_hostname }}-osd-{{ item | regex_replace('/', '') }}" \
           --net host \
           --pid host \
           --privileged \
           -e OSD_DEVICE={{ item }} \
           -e CEPH_DAEMON=OSD_CEPH_DISK_ACTIVATE \
           -v /var/lib/ceph:/var/lib/ceph \
           -v /etc/ceph:/etc/ceph \
           -v /dev:/dev \
           -v /run:/run \
           --entrypoint=/bin/bash \
           {{ ceph_osd_docker_username }}/{{ ceph_osd_docker_imagename }}
  with_items: ceph_osd_docker_devices

- name: manually prepare the disk by co-locating data/journal
  shell: >
         docker exec {{ ansible_hostname }}-osd-{{ item | regex_replace('/', '') }} \
           ceph-disk prepare \
             --cluster ceph \
             --cluster-uuid e9570dd8-03ad-45f0-8a74-ec9b3bb7095f \
             --fs-type ext4 \
             {{ item }}1 {{ item }}2
  with_items: ceph_osd_docker_devices

- name: mount directories and mkfs OSD specifics
  shell: docker exec {{ ansible_hostname }}-osd-{{ item | regex_replace('/', '') }} /entrypoint.sh
  with_items: ceph_osd_docker_devices
  ignore_errors: True

- name: get the OSD number
  shell: docker exec {{ ansible_hostname }}-osd-{{ item | regex_replace('/', '') }} ls /var/lib/ceph/osd/ | sed "s/ceph-//g"
  with_items: ceph_osd_docker_devices
  register: result

- name: start the OSD
  shell: docker exec {{ ansible_hostname }}-osd-{{ item.0 | regex_replace('/', '') }} ceph-osd -i {{ item.1.stdout }}
  with_together:
  - "{{ ceph_osd_docker_devices }}"
  - "{{ result.results }}"

- name: add the host to the CRUSH map
  shell: docker exec {{ ansible_hostname }}-osd-{{ item | regex_replace('/', '') }} ceph osd crush add-bucket {{ ansible_hostname }} host
  with_items: ceph_osd_docker_devices

- name: move the host to be a child in the crush map
  shell: docker exec {{ ansible_hostname }}-osd-{{ item | regex_replace('/', '') }} ceph osd crush move {{ ansible_hostname }} root=default
  with_items: ceph_osd_docker_devices

- name: add the OSD to the new host in the CRUSH map
  shell: docker exec {{ ansible_hostname }}-osd-{{ item.0 | regex_replace('/', '') }} ceph osd crush add osd.{{ item.1.stdout }} 1.0 host={{ ansible_hostname }}
  with_together:
  - "{{ ceph_osd_docker_devices }}"
  - "{{ result.results }}"
