---
- name: ensure conf dirs exist
  file: path={{ item }} state=directory
  with_items:
  - /etc/ceph
  - /var/lib/ceph/
  - /var/lib/ceph/bootstrap-osd
  - /var/lib/ceph/bootstrap-rgw
  - /var/lib/ceph/bootstrap-mds

- name: generate ceph configuration file
  action: config_template
  args:
    src: "{{ playbook_dir }}/templates/ceph.conf.j2"
    dest: /etc/ceph/ceph.conf
    owner: "root"
    group: "root"
    mode: "0644"
    config_overrides: "{{ ceph_conf_overrides }}"
    config_type: ini
