---
- name: run the ceph docker image
  shell: >
         docker run -d -it \
           --name=cephfs-{{ item }} \
           --net=host \
           --privileged \
           -v /dev:/dev \
           -v /run:/run \
           -v /sys:/sys \
           -v /etc/ceph:/etc/ceph \
           -v {{ mount_point }}:/cephfs:shared \
           --entrypoint="/bin/bash" \
           "{{ ceph_client_docker_username }}/{{ ceph_client_docker_imagename }}:{{ ceph_client_docker_image_tag }}"
  with_sequence: start=1 end={{ nclients }}

- name: setup ceph mount point
  shell: docker exec cephfs-1 /bin/bash -c "ceph osd crush tunables legacy"

- name: start the kernel client
  shell: docker exec cephfs-{{ item }} /bin/bash -c "sudo mount.ceph {{ groups['mons'][0] }}:6789:/ /cephfs -v -o name=admin,secret=\`ceph-authtool -p /etc/ceph/ceph.client.admin.keyring\`"
  with_sequence: start=1 end={{ nclients }}

- name: check to make sure it got mounted
  shell: docker run --rm --volumes-from cephfs-{{ item }} alpine sh -c "mount" | grep "cephfs"
  register: mount_out
  failed_when: mount_out.rc != 0
  with_sequence: start=1 end={{ nclients }}
