---
- name: run the ceph fuse docker image
  shell: >
         docker run -d \
           --name=cephfs \
           --net=host \
           --privileged \
           -v /dev:/dev \
           -v /run:/run \
           -v /sys:/sys \
           -v /etc/ceph:/etc/ceph \
           -v {{ mount_point }}:{{ mount_point }}:shared \
           --entrypoint="/bin/bash" \
           "{{ ceph_client_docker_username }}/{{ ceph_client_docker_imagename }}:{{ ceph_client_docker_image_tag }}" \
           -c "ceph-fuse {{ mount_point }} -d -o allow_other"
  when: processes_per_client is not defined

- name: run the ceph fuse docker image
  shell: >
         docker run -d \
           --name=cephfs-{{ item }} \
           --net=host \
           --privileged \
           -v /dev:/dev \
           -v /run:/run \
           -v /sys:/sys \
           -v /etc/ceph:/etc/ceph \
           -v {{ mount_point }}-{{ item }}:{{ mount_point }}-{{ item }}:shared \
           --entrypoint="/bin/bash" \
           "{{ ceph_client_docker_username }}/{{ ceph_client_docker_imagename }}:{{ ceph_client_docker_image_tag }}" \
           -c "ceph-fuse {{ mount_point }}-{{ item }} -d -o allow_other"
  when: processes_per_client is defined
  with_sequence: start=1 end={{ processes_per_client }}

- name: check to make sure it got mounted
  shell: docker run --rm --volumes-from cephfs alpine sh -c "mount" | grep "ceph-fuse"
  register: mount_out
  failed_when: mount_out.rc != 0
  when: processes_per_client is not defined

- name: check to make sure it got mounted
  shell: docker run --rm --volumes-from cephfs-{{ item }} alpine sh -c "mount" | grep "ceph-fuse"
  register: mount_out
  failed_when: mount_out.rc != 0
  when: processes_per_client is defined
  with_sequence: start=1 end={{ processes_per_client }}


