---
- name: run the ceph fuse docker image
  shell: >
         docker run -d \
           --name=cephfs \
           --net=host \
           --privileged \
           -v /dev:/dev \
           -v /run:/run \
           -v /sys:/sys \
           -v /etc/ceph:/etc/ceph \
           --entrypoint=/bin/bash \
           "{{ ceph_client_docker_username }}/{{ ceph_client_docker_imagename }}" \
           -c "mkdir /cephfs; ceph-fuse /cephfs -d -o allow_other"
